# Generated by Django 5.2.5 on 2025-08-07 10:24

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=account.models.ValidPhoneNumberField(max_length=128, region=None, verbose_name='Phone Number'),
        ),
    ]
