# Generated by Django 5.2.5 on 2025-08-07 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_permission_role_rolepermission_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.role'),
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
