# Generated by Django 5.2.5 on 2025-08-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_role_delete_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='account.permission'),
        ),
        migrations.DeleteModel(
            name='RolePermission',
        ),
    ]
