# Generated by Django 5.2.5 on 2025-08-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_role_permissions_delete_rolepermission'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_menus',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='menu.menu'),
        ),
    ]
