# Generated by Django 5.2.5 on 2025-08-09 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='menu.menu'),
            preserve_default=False,
        ),
    ]
