# Generated by Django 5.2.5 on 2025-08-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('ticket', '0002_alter_ticket_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='menu',
        ),
        migrations.AddField(
            model_name='ticket',
            name='menu',
            field=models.ManyToManyField(related_name='menu_tickets', to='menu.menu'),
        ),
    ]
